### PR TITLE
All the SSE arithmetic instructions they are implemented

### PR DESCRIPTION
**Pull request by bencz**
All the vcxproj files are changed to support windows XP too.

### CODE REVIEW

**Comment by arakov** [comment]
Did you test if the projects are compiled correctly for visual studio 2015?

**Comment by arakov** [comment]
And secondly, your editor use CR+LF?

Git shows the the whole file changed, so it is not possible to see the actual change

**Comment by arakov** [comment]
merging

**Comment by bencz** [comment]
Hi 
yes, project build correctly in VS2015, I'm just use vs2015! :)
I do not know why the VS recreate the whole project file...
TO support windows XP, I changed "project->properties->Plataform toolset" from "v140" to "v140_xp"

**Comment by arakov** [comment]
Yes, I saw it already. Your editor do not use  CR+LF for new line. Please change it in VS. It would be better if we will have similar editor settings :)

**Comment by bencz** [comment]
Ok!
Now it's correctly!
https://github.com/bencz/elena-lang/commit/a98b1f06d17586109bd3451fffbba3e0da43c255

**Pull request merged**
